//Ontology export
var baseURI = 'http://microbrew.it/beer.owl#';

exports.prefix = 'PREFIX mb:<http://microbrew.it/beer.owl#> ';

exports.mb = {
//beer
	baseURI : baseURI,
	beer  : ' <' + baseURI + 'Beer> ',
	name : ' <' + baseURI + 'name> ',
	style : ' <' + baseURI + 'hasStyle> ',
	abv : ' <' + baseURI + 'abv> ',
	origin : ' <' + baseURI + 'origin> ',
	bottle : ' <' + baseURI + 'bottle> ',
	image : ' <' + baseURI + 'image> ',
	label : ' <' + baseURI + 'label> ',
	comment : ' <' + baseURI + 'comment> ',
	description : ' <' + baseURI + 'description> ',
	servingType : ' <' + baseURI + 'servingType> ',
	glassType : ' <' + baseURI + 'glassType> ',
	ibu : ' <' + baseURI + 'ibu> ',
	aroma : ' <' + baseURI + 'aroma> ',
	appearance : ' <' + baseURI + 'appearance> ',
	mouthfeel : ' <' + baseURI + 'mouthfeel> ',
	ebc : ' <' + baseURI + 'ebc> ',
	colour : ' <' + baseURI + 'colour> ',
	barcode : ' <' + baseURI + 'barcode> ',
	brewedBy : ' <' + baseURI + 'brewedBy> ',
	brewery : ' <' + baseURI + 'Brewery> ',
	beerstyle : ' <' + baseURI + 'BeerStyle> ',
	grain : ' <' + baseURI + 'Grain> ',
	hasPPG : ' <' + baseURI + 'hasPPG> ',
	hasColour : '<' + baseURI + 'hasColour>',
	fermentables : '<' + baseURI + 'Fermentables>',
	ingredient : '<' + baseURI + 'Ingredient>',
	suppliedBy : '<' + baseURI + 'suppliedBy>',
	extract : '<' + baseURI + 'Extract>',
	yeast : '<' + baseURI + 'Yeast>',
	hops : '<' + baseURI + 'Hops>',
	aalow : '<' + baseURI + 'hasAlphaAcidLowRange>',
	aahigh : '<' + baseURI + 'hasAlphaAcidHighRange>',
	recommendedUsage : '<' + baseURI + 'recommendedUsage>',
	origin : '<' + baseURI + 'origin>',
	flavourDescription : '<' + baseURI + 'flavourDescription>',
	flavour : '<' + baseURI + 'hasFlavour>',
	possibleSubstitutions : '<' + baseURI + 'possibleSubstitutions>',
	fruit : '<' + baseURI + 'Fruit>',
	spice : '<' + baseURI + 'Spice>',
	other : '<' + baseURI + 'Other>',
	userName : '<' + baseURI + 'userName>',
	substitutions : '<' + baseURI + 'possibleSubstitutions>',
	hasID : '<' + baseURI + 'hasID>',
	country : '<' + baseURI + 'Country>'
};
